import "./styles/scss/custom.scss";
import "./styles/styles.css";

import 'bootstrap-icons/font/bootstrap-icons.css';

import NavBar from "./components/NavBar";
import Footer from "./components/Footer";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
